apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrikant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: star-agile-project
  template:
    metadata:
      labels:
        app: star-agile-project
    spec:
      containers:
      - name: my-app
        image: shrikantdevops/healthcare:latest
        ports:
        - containerPort: 8082

---


apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30001
  selector:
    app: star-agile-project 
